check-markit -->   added back the break Parse CLI options and arguments, not sure why this was removed, I think it had to do with a test case

diff --git a/check-markit b/check-markit
--- a/check-markit
+++ b/check-markit
@@ -1,4 +1,6 @@
 #!/bin/bash
+#	check-markit  4.1.135.1074  2020-12-08T13:36:53.680669-06:00 (CST)  https://github.com/BradleyA/markit  master  uadmin  five-rpi3b.cptx86.com 4.1.134  
+#	   check-markit -->   added back the break Parse CLI options and arguments, not sure why this was removed, I think it had to do with a test case  
 #	check-markit  4.1.133.1069  2020-12-06T11:19:55.256722-06:00 (CST)  https://github.com/BradleyA/markit  master  uadmin  five-rpi3b.cptx86.com 4.1.132-10-ge0073d4  
 #	   check-markit markit -->   Production standard 1.3.614 DEBUG variable  Production standard 2.3.614 Log format (WHEN WHERE WHAT Version Line WHO UID:GID [TYPE] Message)  Production standard 0.3.615 --help  
 #	check-markit  4.1.104.1026  2020-11-12T12:52:43.624779-06:00 (CST)  https://github.com/BradleyA/markit  master  uadmin  five-rpi3b.cptx86.com 4.1.103 
@@ -181,7 +183,8 @@ while [[ "${#}" -gt 0 ]] ; do
 #
     -f|--filename)  if [[ "${2}" == "" ]] ; then echo -e "\n${BOLD}    Argument for ${YELLOW}${1}${WHITE} is not found on command line.${NORMAL}\n" ; exit 1 ; fi ; MARKIT_FILE=${2} ; shift 2 ;;  # 9.3.605
     -f=*|--filename=*)  MARKIT_FILE="${1#*=}" ; if [[ "${MARKIT_FILE}" == "" ]] ; then echo -e "\n${BOLD}    Argument for ${YELLOW}${1}${WHITE} is not found on command line.${NORMAL}\n" ; exit 1 ; fi ; shift  ;;  # 9.3.605
-    *) echo -e "\n${BOLD}    Invalid option, ${YELLOW}${1}${WHITE}, try ${YELLOW}--usage${NORMAL}\n" ; exit 1 ; ;; # 9.3.606
+#    *) echo -e "\n${BOLD}    Invalid option, ${YELLOW}${1}${WHITE}, try ${YELLOW}--usage${NORMAL}\n" ; exit 1 ; ;; # 9.3.606
+    *)  break ;; # 9.3.607
   esac
 done
 if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "${YELLOW}DEBUG${WHITE}" "  Variable... MARKIT_FILE >${BOLD}${CYAN}${MARKIT_FILE}${NORMAL}<" 1>&2 ; fi  # 1.3.614
