check-markit   more changes

diff --git a/check-markit b/check-markit
--- a/check-markit
+++ b/check-markit
@@ -1,4 +1,6 @@
 #!/bin/bash
+#	check-markit  3.245.567  2020-01-06T20:24:43.194717-06:00 (CST)  https://github.com/BradleyA/markit  bradley  zero.cptx86.com 3.244  
+#	   check-markit   more changes 
 #	check-markit  3.244.566  2020-01-06T18:59:31.463098-06:00 (CST)  https://github.com/BradleyA/markit  uadmin  five-rpi3b.cptx86.com 3.243-6-ga5de56f  
 #	   check-markit   fisrt sections out dated to display_usage 
 #	check-markit  3.151.311  2019-01-19T23:06:27.618171-06:00 (CST)  https://github.com/BradleyA/markit.git  uadmin  six-rpi3b.cptx86.com 3.150-2-gc8d1aa7  
@@ -36,45 +38,67 @@ echo    "   ${COMMAND_NAME} [--usage | -usage | -u]"
 echo    "   ${COMMAND_NAME} [--version | -version | -v]"
 }
 
-
-
-
-#
+###  Production standard 0.3.550 --help                                                     # 3.550
 display_help() {
-echo -e "\n${NORMAL}${0} - check file release with repository release"
-echo -e "\nUSAGE\n   ${0} [<FILE_NAME>]"
-echo    "   ${0} [--file <PATH>/<FILE_NAME> | -f <PATH>/<FILE_NAME>]"
-echo    "   ${0} [--help | -help | help | -h | h | -? | ?]"
-echo    "   ${0} [--version | -version | -v]"
-echo -e "\nDESCRIPTION"
-#       Displaying help DESCRIPTION in English en_US.UTF-8
+display_usage
+#    Displaying help DESCRIPTION in English en_US.UTF-8, en.UTF-8, C.UTF-8                  # 3.550
+echo -e "\n${BOLD}DESCRIPTION${NORMAL}"
 echo    "Check the release of a file that was marked using markit with the GitHub"
 echo    "repository or Bitbucket repository or GitLab project release.  Check-markit may"
-echo    "require --file option to include the relative or absolute path with the file name."
+echo    "require --file option to include the relative or absolute path with the file"
+echo    "name."
 echo -e "\nCheck-markit only works on files that are marked after 2018-02-27."
 echo -e "\nCheck-markit only works with markit files that used the https:// URLs for"
 echo    "GitHub, Bitbucket, and GitLab repositories.  Check-markit does not currently"
 echo    "support files with SSH URLs for GitHub, Bitbucket, and GitLab repositories."
-#       Displaying help DESCRIPTION in French fr_CA.UTF-8, fr_FR.UTF-8, fr_CH.UTF-8
-if [ "${LANG}" == "fr_CA.UTF-8" ] || [ "${LANG}" == "fr_FR.UTF-8" ] || [ "${LANG}" == "fr_CH.UTF-8" ] ; then
-        echo -e "\n--> ${LANG}"
-        echo    "<votre aide va ici>" # your help goes here
-        echo    "Souhaitez-vous traduire la section description?" # Do you want to translate the description section?
-elif ! [ "${LANG}" == "en_US.UTF-8" ] ; then
-        get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${USER_ID}:${GROUP_ID} ${BOLD}[WARN]${NORMAL}  Your language, ${LANG}, is not supported.  Would you like to translate the description section?" 1>&2
+
+###  Production standard 4.3.550 Documentation Language                                     # 3.550
+#    Displaying help DESCRIPTION in French fr_CA.UTF-8, fr_FR.UTF-8, fr_CH.UTF-8
+if [[ "${LANG}" == "fr_CA.UTF-8" ]] || [[ "${LANG}" == "fr_FR.UTF-8" ]] || [[ "${LANG}" == "fr_CH.UTF-8" ]] ; then
+  echo -e "\n--> ${LANG}"
+  echo    "<votre aide va ici>" # your help goes here
+  echo    "Souhaitez-vous traduire la section description?" # Do you want to translate the description section?
+elif ! [[ "${LANG}" == "en_US.UTF-8" ||  "${LANG}" == "en.UTF-8" || "${LANG}" == "C.UTF-8" ]] ; then  # 3.550
+  new_message "${LINENO}" "${YELLOW}INFO${WHITE}" "  Your language, ${LANG}, is not supported.  Would you like to translate the description section?" 1>&2
 fi
-echo -e "\nEnvironment Variables"
+
+echo -e "\n${BOLD}ENVIRONMENT VARIABLES${NORMAL}"
 echo    "If using the bash shell, enter; 'export DEBUG=1' on the command line to set"
-echo    "the DEBUG environment variable to '1' (0 = debug off, 1 = debug on).  Use the"
-echo    "command, 'unset DEBUG' to remove the exported information from the DEBUG"
-echo    "environment variable.  You are on your own defining environment variables if"
+echo    "the environment variable DEBUG to '1' (0 = debug off, 1 = debug on).  Use the"
+echo    "command, 'unset DEBUG' to remove the exported information from the environment"
+echo    "variable DEBUG.  You are on your own defining environment variables if"
 echo    "you are using other shells."
-echo    "   DEBUG       (default '0')"
-echo -e "\nOPTIONS\n   -f, --file\n      path and file on system '<path>/<file_name>'"
-echo -e "\nDOCUMENTATION\n   https://github.com/BradleyA/markit"
-echo -e "\nEXAMPLES\n   Check file named sample.c release in relative path testfile/ with\n   repository release.\n\n   check-markit -f testfiles/sample.c"
-echo -e "\n   Check file named markit release with repository release.\n\n   check-markit markit\n"
-}
+
+###  Production standard 1.3.550 DEBUG variable                                             # 3.550
+echo    "   DEBUG           (default off '0')  The DEBUG environment variable can be set"   # 3.550
+echo    "                   to 0, 1, 2, 3, 4 or 5.  The setting '' or 0 will turn off"      # 3.550
+echo    "                   all DEBUG messages during execution of this script.  The"       # 3.550
+echo    "                   setting 1 will print all DEBUG messages during execution."      # 3.550
+echo    "                   Setting 2 (set -x) will print a trace of simple commands"       # 3.550
+echo    "                   before they are executed.  Setting 3 (set -v) will print"       # 3.550
+echo    "                   shell input lines as they are read.  Setting 4 (set -e) will"   # 3.550
+echo    "                   exit immediately if non-zero exit status is recieved with"      # 3.550
+echo    "                   some exceptions.  Setting 5 (set -e -o pipefail) will do"       # 3.550
+echo    "                   setting 4 and exit if any command in a pipeline errors.  For"   # 3.550
+echo    "                   more information about the set options, see man bash."          # 3.550
+
+echo -e "\n${BOLD}OPTIONS${NORMAL}"
+echo    "   -f, --file  <PATH>/<FILE_NAME>"
+echo -e "\tInclude the relative or absolute path with the file name"
+
+echo -e "\n${BOLD}DOCUMENTATION${NORMAL}"
+echo    "  https://github.com/BradleyA/markit/blob/master/README.md" 
+
+echo -e "\n${BOLD}EXAMPLES${NORMAL}"
+echo -e "   Check file named sample.c release in relative path testfile/ with\n   repository release."
+echo -e "\t${BOLD}${COMMAND_NAME} -f testfiles/sample.c${NORMAL}\n"
+echo -e "   Check file named markit release with repository release."
+echo -e "\t${BOLD}${COMMAND_NAME} markit${NORMAL}\n"
+
+
+
+
+
 
 #       Date and time function ISO 8601
 get_date_stamp() {
