check-markit -->   Production standard 9.3.606 Parse CLI options and arguments

diff --git a/check-markit b/check-markit
--- a/check-markit
+++ b/check-markit
@@ -1,8 +1,8 @@
 #!/bin/bash
+#	check-markit  4.1.104.1026  2020-11-12T12:52:43.624779-06:00 (CST)  https://github.com/BradleyA/markit  master  uadmin  five-rpi3b.cptx86.com 4.1.103  
+#	   check-markit -->   Production standard 9.3.606 Parse CLI options and arguments  
 #	check-markit  4.1.103.1025  2020-11-12T12:34:18.447690-06:00 (CST)  https://github.com/BradleyA/markit  master  uadmin  five-rpi3b.cptx86.com 4.1.102  
 #	   check-markit -->   change code for none valid option  
-#	check-markit  4.1.102.1024  2020-11-12T12:22:13.526100-06:00 (CST)  https://github.com/BradleyA/markit  master  uadmin  five-rpi3b.cptx86.com 4.1.101  
-#	   check-markit -->   testing  
 #	check-markit  4.1.95.1013  2020-10-30T16:38:42.942185-05:00 (CDT)  https://github.com/BradleyA/markit  master  uadmin  five-rpi3b.cptx86.com 4.1.94 
 #	   check-markit -->   correct incident while working on test case FVT-option-filename-007  
 #	check-markit  4.1.93.1011  2020-10-30T00:13:57.586676-05:00 (CDT)  https://github.com/BradleyA/markit  master  uadmin  five-rpi3b.cptx86.com 4.1.92-2-gb0c441d  
@@ -172,7 +172,7 @@ if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "DEBUG" "  Setting USE
 #    DEBUG
 if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "DEBUG" "  Name_of_command >${SCRIPT_NAME}< Name_of_arg1 >${1}< Name_of_arg2 >${2}< Name_of_arg3 >${3}<  Version of bash ${BASH_VERSION}" 1>&2 ; fi
 
-###  Production standard 9.3.562 Parse CLI options and arguments
+###  Production standard 9.3.606 Parse CLI options and arguments
 while [[ "${#}" -gt 0 ]] ; do
   case "${1}" in
     --help|-help|help|-h|h|-\?)  display_help | more ; exit 0 ;;
@@ -181,7 +181,7 @@ while [[ "${#}" -gt 0 ]] ; do
 #
     -f|--filename)  if [[ "${2}" == "" ]] ; then echo -e "\n${BOLD}    Argument for ${YELLOW}${1}${WHITE} is not found on command line.${NORMAL}\n" ; exit 1 ; fi ; MARKIT_FILE=${2} ; shift 2 ;;  # 9.3.605
     -f=*|--filename=*)  MARKIT_FILE="${1#*=}" ; if [[ "${MARKIT_FILE}" == "" ]] ; then echo -e "\n${BOLD}    Argument for ${YELLOW}${1}${WHITE} is not found on command line.${NORMAL}\n" ; exit 1 ; fi ; shift  ;;  # 9.3.605
-    *) echo -e "\n${BOLD}    Invalid option, ${YELLOW}${1}${WHITE}, try  ${YELLOW}${COMMAND_NAME} --usage${NORMAL}\n" ; exit 1 ; ;; # 9.3.596
+    *) echo -e "\n${BOLD}    Invalid option, ${YELLOW}${1}${WHITE}, try ${YELLOW}--usage${NORMAL}\n" ; exit 1 ; ;; # 9.3.606
   esac
 done
 if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "DEBUG" "  Variable... MARKIT_FILE >${MARKIT_FILE}<" 1>&2 ; fi
