check-markit   testing changes to markit add branch to line 1  #69

diff --git a/check-markit b/check-markit
--- a/check-markit
+++ b/check-markit
@@ -1,4 +1,6 @@
 #!/bin/bash
+#	check-markit  3.258.580  2020-01-14T11:52:17.238547-06:00 (CST)  https://github.com/BradleyA/markit  master  uadmin  five-rpi3b.cptx86.com 3.257  
+#	   check-markit   testing changes to markit add branch to line 1  #69 
 #	check-markit  3.254.576  2020-01-06T22:58:07.389540-06:00 (CST)  https://github.com/BradleyA/markit  bradley  zero.cptx86.com 3.253  
 #	   check-markit    Production standard 5.3.550 Copyright  Production standard 0.3.550 --help  Production standard 4.3.550 Documentation Language  Production standard 1.3.550 DEBUG variable 
 #	check-markit  3.151.311  2019-01-19T23:06:27.618171-06:00 (CST)  https://github.com/BradleyA/markit.git  uadmin  six-rpi3b.cptx86.com 3.150-2-gc8d1aa7  
@@ -24,6 +26,7 @@ CYAN=$(tput   setaf 6)
 WHITE=$(tput  setaf 7)
 
 ###  Production standard 7.0 Default variable value
+FILE_NAME=""
 MARKIT_FILE=""
 
 ###  Production standard 8.3.541 --usage
@@ -153,36 +156,36 @@ while [[ "${#}" -gt 0 ]] ; do
     --help|-help|help|-h|h|-\?)  display_help | more ; exit 0 ;;
     --usage|-usage|usage|-u)  display_usage ; exit 0  ;;
     --version|-version|version|-v)  echo "${SCRIPT_NAME} ${SCRIPT_VERSION}" ; exit 0  ;;
-    -f|--file)  if [[ "${2}" == "" ]] ; then  display_usage ; new_message "${LINENO}" "${RED}ERROR${WHITE}" "  Argument for ${BOLD}${YELLOW}${1}${NORMAL} is not found on command line" 1>&2 ; exit 1 ; fi ; FILE_NAME=${2} ; shift 2 ;;
+    -f|--file)  if [[ "${2}" == "" ]] ; then  display_usage ; new_message "${LINENO}" "${RED}ERROR${WHITE}" "  Argument for ${BOLD}${YELLOW}${1}${NORMAL} is not found on command line" 1>&2 ; exit 1 ; fi ; MARKIT_FILE=${2} ; shift 2 ;;
     *) break ;;
   esac
 done
-if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "DEBUG" "  Variable... ADMUSER >${ADMUSER}< CLUSTER >${CLUSTER}< DATA_DIR >${DATA_DIR}< FILE_NAME >${FILE_NAME}< SSH_USER >${SSH_USER}< USER_HOME >${USER_HOME}<" 1>&2 ; fi
+if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "DEBUG" "  Variable... MARKIT_FILE >${MARKIT_FILE}<" 1>&2 ; fi
 
 ###
 
-#    Check if argument 1 is blank
-if [[ "${1}" == "" ]] ; then
+###  Check if argument 1 is blank
+if [[ "${1}" == "" ]] && [[ "${MARKIT_FILE}" == "" ]] ; then
   display_usage
   new_message "${LINENO}" "${RED}ERROR${WHITE}" "  File not found on command line" 1>&2
   exit 1
 fi
 
-#    Check if argument 1 is -f or --file
+#    Check if argument 1 is found on system
 if [[ "${MARKIT_FILE}" == "" ]] ; then
 #    Locate file in the PATH
   TEMP=$(whereis "${1}")
   MARKIT_FILE=$(echo "${TEMP}" | awk {'print $2'} )
   if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "DEBUG" "  Locate file in the PATH... MARKIT_FILE >${MARKIT_FILE}<" 1>&2 ; fi
-#    Check if MARKIT_FILE is blank
+#    Check if MARKIT_FILE is blank, not found on system
   if [[ "${MARKIT_FILE}" == "" ]] ; then
-    display_usage
     new_message "${LINENO}" "${RED}ERROR${WHITE}" "  ${1} not found; use --file <path>/<file_name> or -f <path>/<file_name> option" 1>&2
+    display_usage
     exit 1
   fi
 fi
 
-#    Parse file name from MARKIT_FILE
+#    Parse file FILE_NAME from MARKIT_FILE
 FILE_NAME=$(echo "${MARKIT_FILE}" | sed 's/.*\///')
 #    Check if file exists and has a size greater than zero || if file exists and is readable
 if [[ ! -s "${MARKIT_FILE}" ]] || [[ ! -r "${MARKIT_FILE}" ]] ; then
