needs more testing with GitLab close #31

diff --git a/check-markit b/check-markit
--- a/check-markit
+++ b/check-markit
@@ -1,4 +1,6 @@
 #!/bin/bash
+#	check-markit  3.50.193  2018-08-05_21:08:54_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.49  
+#	   needs more testing with GitLab close #31 
 #	check-markit  3.49.192  2018-08-05_20:10:13_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.48-1-g36ae19b  
 #	   check-markit work on Gitlab #31 , need to continue testing 
 ###
@@ -15,12 +17,16 @@ echo -e "\nUSAGE\n   ${0} [<FILE_NAME>]"
 echo    "   ${0} [--file <PATH>/<FILE_NAME> | -f <PATH>/<FILE_NAME>]"
 echo    "   ${0} [--help | -help | help | -h | h | -? | ?] [--version | -v]"
 echo -e "\nDESCRIPTION\nCheck the release of a file that was marked using markit with the GitHub"
-echo    "repository release.  check-markit may require --file option to include the"
-echo    "relative or absolute path with the file name."
-echo -e "\ncheck-markit only works on files that are marked with markit release 3.10.142"
+echo    "or GitLab repository release.  Check-markit may require --file option to"
+echo    "include the relative or absolute path with the file name."
+echo -e "\nCheck-markit only works on files that are marked with markit release 3.10.142"
 echo    "(dated 2018-02-27_19:00:09_CST) or later releases.  Markit release 3.10.142"
 echo    "added the repository information to the second line in a marked file.  This"
-echo    "repository information is required for check-markit to locate a file on GitHub."
+echo    "repository information is required for check-markit to locate a file on GitHub"
+echo    "or GitLab."
+echo -e "\nCheck-markit only works with markit files that used the https:// URLs for"
+echo    "GitHub and GitLab repositories.  Check-markit does not currently support files"
+echo    "with SSH URLs for GitHub and GitLab repositories."
 echo -e "\nOPTIONS\n   -f, --file\n      path and file on system '<path>/<file_name>'"
 echo -e "\nDOCUMENTATION\n   https://github.com/BradleyA/markit"
 echo -e "\nEXAMPLES\n   check-markit -f testfiles/sample.c\n\n   Check file named sample.c release in relative path testfile/ with\n   repository release."
@@ -41,7 +47,7 @@ if [ "${1}" == "" ] ; then
 	echo -e "${NORMAL}\n${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:  File not found on command line\n" 1>&2
 	exit 0
 fi
-#	Check if argument 1 is -f or --file the path is reqired to be included 
+#	Check if argument 1 is -f or --file
 if [ "${1}" == "--file" ] || [ "${1}" == "-f" ] ; then
 	#       Check if argument 2 is blank
 	if [ "${2}" == "" ] ; then
@@ -55,13 +61,14 @@ else
 	TEMP=`whereis "${1}"`
 	MARKIT_FILE=$(echo ${TEMP} | awk {'print $2'} )
 	if [ "${DEBUG}" == "1" ] ; then echo -e ">DEBUG ${LINENO}  MARKIT_FILE ${MARKIT_FILE}<< FILE_NAME ${FILE_NAME}<< REPOSITORY_COMMAND ${REPOSITORY_COMMAND}<< MARKIT_FILE_RELEASE ${MARKIT_FILE_RELEASE}<< " 1>&2 ; fi
-	#       Check if TEMP is blank
+	#       Check if MARKIT_FILE is blank
 	if [ "${MARKIT_FILE}" == "" ] ; then
 		display_help
 		echo -e "${NORMAL}\n${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:  ${1} not found; use --file <path>/<file_name> or -f <path>/<file_name> option\n" 1>&2
 		exit 0
 	fi
 fi
+#	Parse file name from MARKIT_FILE
 FILE_NAME=`echo ${MARKIT_FILE} | sed 's/.*\///'`
 #       Check if file exists and has a size greater than zero || if file exists and is readable
 if [ ! -s ${MARKIT_FILE} ] || [ ! -r ${MARKIT_FILE} ] ; then
@@ -74,7 +81,7 @@ if [ "${DEBUG}" == "1" ] ; then echo -e ">DEBUG ${LINENO}  MARKIT_FILE ${MARKIT_
 #	Check file to determine if it was marked before markit release 3.10.142
 #	if !  `echo "${REPOSITORY_COMMAND}" | grep -q "https"`  ; then
 if ! grep -q "https" <<< ${REPOSITORY_COMMAND}  ; then
-	echo -e "\n${NORMAL}${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:  ${MARKIT_FILE} is not marked with markit or the --file option was not used or git origin did not include https address (git remote -v) when marked or checked or was marked with a release before markit 3.10.142\n" 1>&2
+	echo -e "\n${NORMAL}${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:  ${MARKIT_FILE} is not marked with markit or the --file option was not used or git origin did not include https address (git remote -v) when marked or file was marked with a release before markit 3.10.142\n" 1>&2
 	exit
 fi
 ###
@@ -88,21 +95,19 @@ if grep -q "github" <<< ${REPOSITORY_COMMAND} ; then
 	REPOSITORY_COMMAND="curl \-L ${REPOSITORY_COMMAND}/tarball | tar --directory /tmp/markit-temp -xzf - "
 elif grep -q "gitlab" <<< ${REPOSITORY_COMMAND} ; then
 	echo -e "${NORMAL}\n${0} ${LINENO} [${BOLD}INFO${NORMAL}]:  Checking GitLab for ${BOLD}${FILE_NAME}${NORMAL} repository release information\n" 1>&2
-	echo ">>>> needs to be completed #31 <<<<<<<<<<<<"
 	PROJECT_NAME=`echo ${REPOSITORY_COMMAND} | sed 's/^https:\/\/.*\/.*\///' | sed 's/\.git$//'`
-	echo ${PROJECT_NAME}
 	REPOSITORY_COMMAND=`echo ${REPOSITORY_COMMAND} | sed 's/\.git$/\/-\/archive\/master\//'`
 	if [ "${DEBUG}" == "1" ] ; then echo -e ">DEBUG ${LINENO}  MARKIT_FILE ${MARKIT_FILE}<< FILE_NAME ${FILE_NAME}<< REPOSITORY_COMMAND ${REPOSITORY_COMMAND}<< MARKIT_FILE_RELEASE ${MARKIT_FILE_RELEASE}<< " 1>&2 ; fi
 	REPOSITORY_COMMAND="curl \-L ${REPOSITORY_COMMAND}${PROJECT_NAME}-master.tar.gz | tar --directory /tmp/markit-temp -xzf - "
 	if [ "${DEBUG}" == "1" ] ; then echo -e ">DEBUG ${LINENO}  MARKIT_FILE ${MARKIT_FILE}<< FILE_NAME ${FILE_NAME}<< REPOSITORY_COMMAND ${REPOSITORY_COMMAND}<< MARKIT_FILE_RELEASE ${MARKIT_FILE_RELEASE}<< " 1>&2 ; fi
 else 
 	if [ "${DEBUG}" == "1" ] ; then echo -e ">DEBUG ${LINENO}  MARKIT_FILE ${MARKIT_FILE}<< FILE_NAME ${FILE_NAME}<< REPOSITORY_COMMAND ${REPOSITORY_COMMAND}<< MARKIT_FILE_RELEASE ${MARKIT_FILE_RELEASE}<< " 1>&2 ; fi
-	echo ">>>> OTHER like bitbucket, Codebase, Assembla, Fog Creek Kiln, etc   <<<<<"
-	echo ">>>> needs to be completed #31 <<<<<<<<<<<<"
+	echo    ">>>> Repository using SSH URLs  <<<<<"
+	echo    ">>>> or other repository like bitbucket, Codebase, Assembla, Fog Creek Kiln, etc   <<<<<"
 	exit
 fi
-if [ "${DEBUG}" == "1" ] ; then echo -e ">DEBUG ${LINENO}  MARKIT_FILE ${MARKIT_FILE}<< FILE_NAME ${FILE_NAME}<< REPOSITORY_COMMAND ${REPOSITORY_COMMAND}<< MARKIT_FILE_RELEASE ${MARKIT_FILE_RELEASE}<< " 1>&2 ; fi
 ###
+if [ "${DEBUG}" == "1" ] ; then echo -e ">DEBUG ${LINENO}  MARKIT_FILE ${MARKIT_FILE}<< FILE_NAME ${FILE_NAME}<< REPOSITORY_COMMAND ${REPOSITORY_COMMAND}<< MARKIT_FILE_RELEASE ${MARKIT_FILE_RELEASE}<< " 1>&2 ; fi
 mkdir /tmp/markit-temp
 eval ${REPOSITORY_COMMAND}
 FILE_NAME_LOCATION=`find /tmp/markit-temp -type f -name ${FILE_NAME} -print`
