check-markit -->   check if file starts with '-'

diff --git a/check-markit b/check-markit
--- a/check-markit
+++ b/check-markit
@@ -1,4 +1,6 @@
 #!/bin/bash
+#	check-markit  4.1.136.1076  2020-12-08T13:59:36.981110-06:00 (CST)  https://github.com/BradleyA/markit  master  uadmin  five-rpi3b.cptx86.com 4.1.135-1-gb6bfd83  
+#	   check-markit -->   check if file starts with '-'  
 #	check-markit  4.1.135.1074  2020-12-08T13:36:53.680669-06:00 (CST)  https://github.com/BradleyA/markit  master  uadmin  five-rpi3b.cptx86.com 4.1.134  
 #	   check-markit -->   added back the break Parse CLI options and arguments, not sure why this was removed, I think it had to do with a test case  
 #	check-markit  4.1.133.1069  2020-12-06T11:19:55.256722-06:00 (CST)  https://github.com/BradleyA/markit  master  uadmin  five-rpi3b.cptx86.com 4.1.132-10-ge0073d4  
@@ -200,11 +202,13 @@ fi
 
 #    Check if argument 1 is found on system
 if [[ "${MARKIT_FILE}" == "" ]] ; then
-#    Locate file in the PATH
+  #    check if first character is a '-'
+  if [[ "${1:0:1}"  == "-" ]] ; then echo -e "\n${BOLD}    Invalid option, ${YELLOW}${1}${WHITE}, try ${YELLOW}--usage${NORMAL}\n" ; exit 1 ; fi
+  #    Locate file in the PATH
   TEMP=$(whereis "${1}")
   MARKIT_FILE=$(echo "${TEMP}" | awk '{print $2}' )
   if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "${YELLOW}DEBUG${WHITE}" "  Locate file in the PATH... MARKIT_FILE >${BOLD}${CYAN}${MARKIT_FILE}${NORMAL}<" 1>&2 ; fi  # 1.3.614
-#    Check if MARKIT_FILE is blank, not found on system
+  #    Check if MARKIT_FILE is blank, not found on system
   if [[ "${MARKIT_FILE}" == "" ]] ; then
     new_message "${LINENO}" "${RED}ERROR${WHITE}" "  ${1} not found; use --file <path>/<file_name> or -f <path>/<file_name> option" 1>&2
     display_usage
