testing failed login #30

diff --git a/markit b/markit
--- a/markit
+++ b/markit
@@ -1,21 +1,7 @@
 #!/bin/bash
+#	markit  3.61.204  2018-08-09_11:04:14_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.60  
+#	   testing failed login #30 
 #	markit  3.60.203  2018-08-09_10:59:34_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.59  
-#	   testing failed login #30 
-#	markit  3.59.202  2018-08-09_10:46:16_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.58  
-#	   testing failed login #30 
-#	markit  3.58.201  2018-08-09_10:45:04_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.57  
-#	   testing failed login #30 
-#	markit  3.57.200  2018-08-09_10:43:39_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.56  
-#	   testing failed login #30 
-#	markit  3.56.199  2018-08-09_10:41:20_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.55  
-#	   testing failed login #30 
-#	markit  3.55.198  2018-08-09_10:39:44_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.54  
-#	   testing failed login #30 
-#	markit  3.54.197  2018-08-09_10:36:08_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.53  
-#	   testing failed login #30 
-#	markit  3.53.196  2018-08-09_10:26:33_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.52  
-#	   testing failed login #30 
-#	markit  3.52.195  2018-08-09_10:24:27_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.51  
 #	   testing failed login #30 
 ###
 #	set -x
@@ -228,10 +214,9 @@ echo ${NORMAL}
 if ! [ "${FILE_RELEASE}" == "${CURRENT_RELEASE}" ] ; then
 	git tag -a ${FILE_RELEASE} -m "${FILE_MESSAGE}"
 #	Push changes to GitHub repository or GitLab project
-	git push --follow-tags  || { echo -e "\n${NORMAL}${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:\n\tIf invalid username or password message then enter the following\n\tcommand to complete pushing marked file(s) with the correcet password;\n\t\t'${BOLD}git push --follow-tags${NORMAL}'\n\tIf markit failed to push because the repository contains other work\n\tthat is not in your local clone.  Then enter the following\n\tcommands to pull the other changes and push the marked file(s)\n\t;'${BOLD}'git pull'\n\t\t'git push --follow-tags${NORMAL}'" ; exit 1; }
+	git push --follow-tags  || { echo -e "\n${NORMAL}${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:\n\tIf invalid username or password message then enter the following\n\tcommand to complete pushing marked file(s) with the correcet password;\n\t\t'${BOLD}git push --follow-tags${NORMAL}'\n\tIf markit failed to push because the repository contains other work\n\tthat is not in your local clone.  Then enter the following\n\tcommands to pull the other changes and push your marked file(s)\n\t\t'${BOLD}'git pull'\n\t\t'git push --follow-tags${NORMAL}'" ; exit 1; }
 else
 #	Push changes to GitHub repository or GitLab project
-	git push || { echo -e "\n${NORMAL}${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:\n\tIf invalid username or password, enter  '${BOLD}git push${NORMAL}' to complete push.\n\t remote respoitory contains new work  XXXXX<><><><><\n\tEnter; '${BOLD}git push${NORMAL}' to complete pushing marked file(s)." ; exit 1; }
+	git push || { echo -e "\n${NORMAL}${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:\n\tIf invalid username or password message then enter the following\n\tcommand to complete pushing marked file(s) with the correcet password;\n\t\t'${BOLD}git push${NORMAL}'\n\tIf markit failed to push because the repository contains other work\n\tthat is not in your local clone.  Then enter the following\n\tcommands to pull the other changes and push your marked file(s)\n\t\t'${BOLD}'git pull'\n\t\t'git push${NORMAL}'" ; exit 1; }
 fi
 ###
-'git pull'
