check argument $1 complete and tested, closes #3

diff --git a/markit b/markit
--- a/markit
+++ b/markit
@@ -1,4 +1,6 @@
 #!/bin/bash
+#	markit	3.1.53	2018-02-08_13:52:12_CST uadmin six-rpi3b.cptx86.com 3.1-10-g656b65b 
+#	check argument $1 complete and tested, closes #3 
 #	markit	3.1.48	2018-02-07_22:39:36_CST uadmin six-rpi3b.cptx86.com 3.1-5-ge772a21 
 #	Closes #2 
 #	markit	3.1.43	2018-02-07_17:12:56_CST uadmin six-rpi3b.cptx86.com 3.1 
@@ -65,7 +67,6 @@ UNTRACKED_FILES=${1:-no}
 CURRENT_RELEASE=`git tag | tail -1`
 BEGIN_COMMENT_CHAR=""
 END_COMMENT_CHAR=""
-FILE_LIST=`git status -s --untracked-files=${UNTRACKED_FILES} | awk '{print $2}'`
 NUMBER_COMMITS=`git rev-list HEAD | wc -l`	
 TEMP_FILE="TEMP_MARKIT_FILE"
 TIME_STAMP=`date +%Y-%m-%d_%H:%M:%S_%Z`
@@ -73,17 +74,21 @@ TIME_STAMP=`date +%Y-%m-%d_%H:%M:%S_%Z`
 FILE_MESSAGE=""
 FILE_RELEASE=""
 FILE_TEMP="TEMP_MARKIT_FILE"
+###
+#	Check arguement 1 for --untracked-files
+if [ "$1" != "no" ] && [ "$1" != "normal" ] && [ "$1" != "all" ] && [ "$1" != "" ] ; then
+	display_help
+	echo -e "${0} ${LINENO} [ERROR]:	First arguement, ${1}, is NOT no, normal, all.\n"	1>&2
+	exit 0
+fi
+FILE_LIST=`git status -s --untracked-files=${UNTRACKED_FILES} | awk '{print $2}'`
 #	Check if ${FILE_LIST} is zero length
 if [ -z "${FILE_LIST}" ] ; then
-	echo -e "${0} ${LINENO} [ERROR]:	No file(s) found to mark and push to github.\n"	1>&2
-	git status
 	display_help
+	git status
+	echo -e "${0} ${LINENO} [ERROR]:	No file(s) found to mark and push to github.\n"	1>&2
 	exit 1
 fi
-###
-# >>>	Need to add a check for argument, display_help, exit 1; $1 variable no, normal, all
-# >>>	add code here
-###
 #	Prompt for release number
 echo -e "Files to be marked and pushed to github:\n${FILE_LIST}"
 echo    "Current release number: ${CURRENT_RELEASE} "
@@ -93,8 +98,8 @@ if [ -z ${FILE_RELEASE} ] ; then
 	FILE_RELEASE=${CURRENT_RELEASE}
 fi
 if [ -z ${FILE_RELEASE} ] ; then
-	echo -e "${0} ${LINENO} [ERROR]:	No release number to mark and push to github.\n"       1>&2
 	display_help
+	echo -e "${0} ${LINENO} [ERROR]:	No release number to mark and push to github.\n"       1>&2
 	exit 1
 fi
 echo -e "${0} ${LINENO} [INFO]:	Using release number: ${FILE_RELEASE}"	1>&2
@@ -109,8 +114,8 @@ read BEGIN_COMMENT_CHAR
 #	>>>	read END_COMMENT_CHAR
 #	>>>	if [ -z ${END_COMMENT_CHAR} ] ; then ERROR message display_help, exit 1
 if [ -z ${BEGIN_COMMENT_CHAR} ] ; then
-	echo -e "${0} ${LINENO} [ERROR]:        Single-line comment character(s) is required.\n"       1>&2
 	display_help
+	echo -e "${0} ${LINENO} [ERROR]:        Single-line comment character(s) is required.\n"       1>&2
 	exit 1
 fi
 #	Prompt for single line change description
@@ -119,8 +124,8 @@ fi
 echo "Enter a one line description about the changes:"
 read FILE_MESSAGE
 if [ -z "${FILE_MESSAGE}" ] ; then
-	echo -e "${0} ${LINENO} [ERROR]:        Single-line description is required.\n"       1>&2
 	display_help
+	echo -e "${0} ${LINENO} [ERROR]:        Single-line description is required.\n"       1>&2
 	exit 1
 fi
 #	Mark each file
@@ -139,6 +144,7 @@ done
 	git commit -m "${FILE_MESSAGE}"
 #	Check if release number is new then add tag reference with new release number
 # >>>	   think about changing == to >= (are all release numbers? no A.01 ?)
+# >>>	        is v1.0 > v2.0 or v1.1 
 if ! [ "${FILE_RELEASE}" == "${CURRENT_RELEASE}" ] ; then
 	git tag -a ${FILE_RELEASE} -m "${FILE_MESSAGE}"
 #	Push changes to github repository
