changes from standard template and shellcheck

diff --git a/markit b/markit
--- a/markit
+++ b/markit
@@ -1,4 +1,6 @@
 #!/bin/bash
+#	markit  3.135.291  2018-11-15T17:17:23.880721-06:00 (CST)  https://github.com/BradleyA/markit  uadmin  one-rpi3b.cptx86.com 3.134  
+#	   changes from standard template and shellcheck 
 #	markit  3.134.290  2018-11-14T17:18:53.064988-06:00 (CST)  https://github.com/BradleyA/markit  uthree  three.cptx86.com 3.133  
 #	   update display_help to support more 
 #	markit  3.133.289  2018-11-14T12:02:17.185858-06:00 (CST)  https://github.com/BradleyA/markit  uthree  three.cptx86.com 3.132  
@@ -72,21 +74,21 @@ fi
 
 #       Date and time function ISO 8601
 get_date_stamp() {
-DATE_STAMP=`date +%Y-%m-%dT%H:%M:%S.%6N%:z`
-TEMP=`date +%Z`
-DATE_STAMP=`echo "${DATE_STAMP} (${TEMP})"`
+DATE_STAMP=$(date +%Y-%m-%dT%H:%M:%S.%6N%:z)
+TEMP=$(date +%Z)
+DATE_STAMP="${DATE_STAMP} (${TEMP})"
 }
 
 #       Fully qualified domain name FQDN hostname
-LOCALHOST=`hostname -f`
+LOCALHOST=$(hostname -f)
 
 #       Version
-SCRIPT_NAME=`head -2 ${0} | awk {'printf$2'}`
-SCRIPT_VERSION=`head -2 ${0} | awk {'printf$3'}`
+SCRIPT_NAME=$(head -2 "${0}" | awk {'printf $2'})
+SCRIPT_VERSION=$(head -2 "${0}" | awk {'printf $3'})
 
 #       UID and GID
-USER_ID=`id -u`
-GROUP_ID=`id -g`
+USER_ID=$(id -u)
+GROUP_ID=$(id -g)
 
 #       Default help and version arguments
 if [ "$1" == "--help" ] || [ "$1" == "-help" ] || [ "$1" == "help" ] || [ "$1" == "-h" ] || [ "$1" == "h" ] || [ "$1" == "-?" ] ; then
@@ -99,7 +101,7 @@ if [ "$1" == "--version" ] || [ "$1" == "-version" ] || [ "$1" == "version" ] ||
 fi
 
 #       DEBUG
-if [ "${DEBUG}" == "1" ] ; then get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${0} ${SCRIPT_VERSION} ${LINENO} ${BOLD}[DEBUG]${NORMAL}  ${LOCALHOST}  ${USER}  ${USER_ID} ${GROUP_ID}  Name_of_command >${0}< Name_of_arg1 >${1}<" 1>&2 ; fi
+if [ "${DEBUG}" == "1" ] ; then get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${USER_ID}:${GROUP_ID} ${BOLD}[DEBUG]${NORMAL}  Name_of_command >${0}< Name_of_arg1 >${1}< Name_of_arg2 >${2}< Name_of_arg3 >${3}<  Version of bash ${BASH_VERSION}" 1>&2 ; fi
 
 ###
 #       Check if bash-completion/completions/git file on system
@@ -107,23 +109,22 @@ if [ -e /usr/share/bash-completion/completions/git ] ; then
 	#	This is to support __gitdir in the following section
 	source /usr/share/bash-completion/completions/git
 else
-	get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${0} ${SCRIPT_VERSION} ${LINENO} ${BOLD}[INFO]${NORMAL}  ${LOCALHOST}  ${USER}  ${USER_ID} ${GROUP_ID}  /usr/share/bash-completion/completions/git NOT found" 1>&2
+	get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${USER_ID}:${GROUP_ID} ${BOLD}[INFO]${NORMAL}  /usr/share/bash-completion/completions/git NOT found" 1>&2
 fi
 
 #	Check if in Git repository
 if ! $( __gitdir > /dev/null 2>&1 ) ; then
-	echo -e "`pwd` Check if you are in a Git repository and you have Git permission." 1>&2
+	echo -e "Check if you are in a Git repository and you have Git permission.  Current directory $(pwd)" 1>&2
 	exit 0
 fi
 #	Check if remote git repository has been setup #28
-git rev-list HEAD 1> /dev/null || { get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${0} ${SCRIPT_VERSION} ${LINENO} ${BOLD}[ERROR]${NORMAL}  ${LOCALHOST}  ${USER}  ${USER_ID} ${GROUP_ID}   Remote repository has not been setup or git cloned <remote-repository> was not used to pull remote repository before using markit." 1>&2 ; exit 1; }
+git rev-list HEAD 1> /dev/null || { get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${USER_ID}:${GROUP_ID} ${BOLD}[ERROR]${NORMAL}  Remote repository has not been setup or git clone <remote-repository> was not used to pull remote repository before using markit." 1>&2 ; exit 1; }
 
 #
 UNTRACKED_FILES=${1:-no}
 BEGIN_COMMENT_CHAR=""
 END_COMMENT_CHAR=""
-NUMBER_COMMITS=`git rev-list HEAD | wc -l`	
-REMOTE_REPOSITORY=`git ls-remote --get-url`
+REMOTE_REPOSITORY=$(git ls-remote --get-url)
 TEMP_FILE="TEMP_MARKIT_FILE"
 #	The FILE_MESSAGE is a one line breif description about the changes.
 FILE_MESSAGE=""
@@ -134,7 +135,7 @@ if ! [ "$(git tag)" == "" ] ; then
 # >>> # ??	read about this online: 
 # >>>		need to check this out later: git for-each-ref refs/tags --sort=-taggerdate --format='%(refname:short)' --count=1
 # >>>		latest tagged commit across all branches
-	CURRENT_RELEASE=`git describe --tags $(git rev-list --tags --max-count=1)`
+	CURRENT_RELEASE=$(git describe --tags $(git rev-list --tags --max-count=1))
 else
 	CURRENT_RELEASE="0.01"
 fi
