testing failed login #30

diff --git a/markit b/markit
--- a/markit
+++ b/markit
@@ -1,4 +1,6 @@
 #!/bin/bash
+#	markit  3.52.195  2018-08-09_10:24:27_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.51  
+#	   testing failed login #30 
 #	markit  3.51.194  2018-08-09_10:13:46_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.50  
 #	   testing failed login 
 #	markit  3.41.182  2018-08-04_22:33:08_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.40  
@@ -218,9 +220,16 @@ echo ${NORMAL}
 if ! [ "${FILE_RELEASE}" == "${CURRENT_RELEASE}" ] ; then
 	git tag -a ${FILE_RELEASE} -m "${FILE_MESSAGE}"
 #	Push changes to GitHub repository or GitLab project
-	git push --follow-tags  || { echo -e "\n${NORMAL}${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:	login failed, or\n\tremote respoitory contains new work or password is NOT correct.\n\tEnter;  '${BOLD}git push --follow-tags${NORMAL}'  to complete pushing marked file(s)." ; exit 1; }
+	git push --follow-tags  || { echo -e "\n${NORMAL}${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:\n\tIf invalid username or password, Enter;  '${BOLD}git push --follow-tags${NORMAL}'  to complete push.\n\tremote respoitory contains new work XXXX<><><><.\n\tEnter;  '${BOLD}git push --follow-tags${NORMAL}'  to complete pushing marked file(s)." ; exit 1; }
 else
 #	Push changes to GitHub repository or GitLab project
-	git push || { echo -e "\n${NORMAL}${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:	login failed, or\n\tremote respoitory contains new work or password is NOT correct.\n\tEnter; '${BOLD}git push${NORMAL}' to complete pushing marked file(s)." ; exit 1; }
+	git push || { echo -e "\n${NORMAL}${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:\n\tIf invalid username or password, enter  '${BOLD}git push${NORMAL}' to complete push.\n\t remote respoitory contains new work  XXXXX<><><><><\n\tEnter; '${BOLD}git push${NORMAL}' to complete pushing marked file(s)." ; exit 1; }
 fi
 ###
+remote: Invalid username or password.
+fatal: Authentication failed for 'https://github.com/BradleyA/markit/'
+
+/usr/local/bin/markit 219 [ERROR]:	login failed, or
+	remote respoitory contains new work or password is NOT correct.
+	Enter; 'git push --follow-tags' to complete pushing marked file(s).
+
