need more work but close #29

diff --git a/markcheck b/markcheck
--- a/markcheck
+++ b/markcheck
@@ -1,4 +1,6 @@
 #!/bin/bash
+#	markcheck  3.29.170  2018-08-02_23:18:07_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.28  
+#	   need more work but close #29 
 #	markcheck  3.28.169  2018-08-02_23:08:58_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.27  
 #	   parsed MARKIT_FILE now put it into one line with error detction #29 
 #	markcheck  3.27.168  2018-08-02_15:22:11_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.26  
@@ -59,7 +61,7 @@ git rev-list HEAD 1> /dev/null || { echo -e "\n${NORMAL}${0} ${LINENO} [${BOLD}E
 ##################################
 #       Check if argument 1 is blank
 if [ "${1}" == "" ] ; then
-	echo -e "${NORMAL}\n${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:	File not found on command line\n" 1>&2
+	echo -e "${NORMAL}\n${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:  File not found on command line\n" 1>&2
 	display_help
 	exit 0
 fi
@@ -67,7 +69,7 @@ fi
 if [ "${1}" == "--file" ] || [ "${1}" == "-f" ] ; then
 	#       Check if argument 2 is blank
 	if [ "${2}" == "" ] ; then
-		echo -e "${NORMAL}\n${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:	File not found on command line after --file or -f option\n" 1>&2
+		echo -e "${NORMAL}\n${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:  File not found on command line after --file or -f option\n" 1>&2
 		display_help
 		exit 0
 	fi
@@ -79,19 +81,17 @@ else
 	echo  "${LINENO} temp = ${TEMP}"
 	MARKIT_FILE=$(echo ${TEMP} | awk {'print $2'} )
 	echo  "${LINENO} MARKIT_FILE = ${MARKIT_FILE}"
-exit
-	MARKIT_FILE=`whereis ${1}` | awk {'print$2'} 1> /dev/null || { echo -e "\n${NORMAL}${0} ${LINENO} [${BOLD}ERROR${NORMAL}]: ${MARKIT_FILE} file not found in PATH\n${PATH}\n >>>> is it executable <<<<<< remove this later  <<<<< " ; exit 1; }
+###	<><<>< needs more testing  >>>>>  #29
+	MARKIT_FILE=$(echo ${TEMP} | awk {'print $2'} ) 1> /dev/null || { echo -e "\n${NORMAL}${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:  ${MARKIT_FILE} file not found in PATH\n${PATH}\n >>>> is it executable <<<<<< remove this later  <<<<< " ; exit 1; }
 fi
 
-
-echo  ${LINENO}${MARKIT_FILE}
+echo  "${LINENO} MARKIT_FILE = ${MARKIT_FILE}"
 exit
 
-
-
+###
 #       Check if MARKIT_FILE file exists and has a size greater than zero
 if [ ! -e ${MARKIT_FILE} ] || [ ! -s ${MARKIT_FILE} ] ; then
-       	echo -e "${NORMAL}\n${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:     ${MARKIT_FILE} file is not found or is empty\n" 1>&2
+       	echo -e "${NORMAL}\n${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:  ${MARKIT_FILE} file is not found or is empty\n" 1>&2
 	exit 1
 fi
 ###
