testing failed login; cleanup of debugging for #9

diff --git a/markit b/markit
--- a/markit
+++ b/markit
@@ -1,4 +1,6 @@
 #!/bin/bash
+#	markit	3.1.77	2018-02-11_22:03:37_CST uadmin six-rpi3b.cptx86.com 1.6-35-gf58eb9f 
+#	testing failed login; cleanup of debugging for #9 
 #	markit	3.1.76	2018-02-11_22:00:47_CST uadmin six-rpi3b.cptx86.com 1.6-34-ga4915ea 
 #	testing failed login; cleanup of debugging for #9 
 #	markit	3.1.74	2018-02-11_21:35:56_CST uadmin six-rpi3b.cptx86.com 1.6-32-g232fc5f 
@@ -216,7 +218,7 @@ if ! [ "${FILE_RELEASE}" == "${CURRENT_RELEASE}" ] ; then
 	git push --follow-tags
 else
 #	Push changes to GitHub repository
-	git push || { echo "${0} ${LINENO} [ERROR]:	Login fail,\n\tGitHub respoitory or GitHub password NOT correct.\n\tEnter; 'git push' complete push of marked file(s)." ; exit 1; }
+	git push || { echo -e "${0} ${LINENO} [ERROR]:	GitHub login fail,\n\tRespoitory or password NOT correct.\n\tEnter; 'git push' complete push of marked file(s)." ; exit 1; }
 fi
 echo -e "${0} ${LINENO} [INFO]:	Done.\n"	1>&2
 ###
