clean up test code #61

diff --git a/markit b/markit
--- a/markit
+++ b/markit
@@ -1,4 +1,6 @@
 #!/bin/bash
+#	markit  3.186.355  2019-02-07T20:16:35.704322-06:00 (CST)  https://github.com/BradleyA/markit  uadmin  six-rpi3b.cptx86.com 3.185  
+#	   clean up test code #61 
 #	markit  3.185.354  2019-02-07T17:14:04.729095-06:00 (CST)  https://github.com/BradleyA/markit  uadmin  six-rpi3b.cptx86.com 3.184  
 #	   test local tag ever commit test 
 #	markit  3.184.353  2019-02-07T13:16:53.728076-06:00 (CST)  https://github.com/BradleyA/markit  uadmin  six-rpi3b.cptx86.com 3.183  
@@ -160,7 +162,7 @@ if ! [ "$(git tag)" == "" ] ; then
 # >>>		latest tagged commit across all branches
 	CURRENT_RELEASE=$(git describe --tags $(git rev-list --tags --max-count=1))
 else
-	CURRENT_RELEASE="0.01"
+	CURRENT_RELEASE="0.1"
 fi
 
 #	Check arguement 1 for --untracked-files
@@ -312,35 +314,24 @@ for FILE_NAME in ${FILE_LIST} ; do
 done
 echo "${NORMAL}"
 
-#	Commit staged file(s)
-	git commit -m "${FILE_MESSAGE}"
+#	Commit file(s)
+git commit -m "${FILE_MESSAGE}"
+
+#	Tag file(s)
+git tag -a ${FILE_RELEASE} -m "${FILE_MESSAGE}"
 
 #	If MARKITLOCAL not set, git push to remote repository
 if [ "${MARKITLOCAL}" == "0" ] ; then
+#	Push changes to GitHub repository or Bitbucket repository or GitLab project
+	git push --follow-tags  || { get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${USER_ID}:${GROUP_ID} ${BOLD}[ERROR]${NORMAL}\n\tIf invalid username or password message then enter the following\n\tcommand to complete pushing marked file(s) with the correcet password;\n\t\t'${BOLD}git push --follow-tags${NORMAL}'\n\n\tIf markit failed to push because the repository contains other work\n\tthat is not in your local Git repository.  Then enter the following\n\tcommands to pull the other changes then push your marked file(s);\n\t\t${BOLD}'git pull'\n\t\t'git push --follow-tags${NORMAL}'" ; exit 1; }
+#	Notify user how to view remote repository
+	echo -e "\nFiles marked and stored in  ${BOLD}remote${NORMAL}  repository."
+	echo    "View commits example:  '${BOLD}git log --graph --decorate --oneline --color --stat${NORMAL}'"
 
-##		If new release number, include git tag before git push
-#		if ! [ "${FILE_RELEASE}" == "${CURRENT_RELEASE}" ] ; then
-		git tag -a ${FILE_RELEASE} -m "${FILE_MESSAGE}"
-
-#	#		Push changes to GitHub repository or Bitbucket repository or GitLab project
-		git push --follow-tags  || { get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${USER_ID}:${GROUP_ID} ${BOLD}[ERROR]${NORMAL}\n\tIf invalid username or password message then enter the following\n\tcommand to complete pushing marked file(s) with the correcet password;\n\t\t'${BOLD}git push --follow-tags${NORMAL}'\n\n\tIf markit failed to push because the repository contains other work\n\tthat is not in your local Git repository.  Then enter the following\n\tcommands to pull the other changes then push your marked file(s);\n\t\t${BOLD}'git pull'\n\t\t'git push --follow-tags${NORMAL}'" ; exit 1; }
-#		else
-
-#	#		Push changes to GitHub repository or Bitbucket repository or GitLab project
-#			git push || { get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${USER_ID}:${GROUP_ID} ${BOLD}[ERROR]${NORMAL}\n\tIf invalid username or password message then enter the following\n\tcommand to complete pushing marked file(s) with the correcet password;\n\t\t'${BOLD}git push${NORMAL}'\n\n\tIf markit failed to push because the repository contains other work\n\tthat is not in your local Git repository.  Then enter the following\n\tcommands to pull the other changes then push your marked file(s);\n\t\t${BOLD}'git pull'\n\t\t'git push${NORMAL}'" ; exit 1; }
-#		fi
-
-#	If MARKITLOCAL AND new release number, git tag to local repository and notify user
-elif [ "${MARKITLOCAL}" == "1" ] && ! [ "${FILE_RELEASE}" == "${CURRENT_RELEASE}" ] ; then
-	git tag -a ${FILE_RELEASE} -m "${FILE_MESSAGE}"
-	echo -e "\nFiles marked for  ${BOLD}local${NORMAL}  repository."
-	echo    "Enter '${BOLD}git log --graph --decorate --oneline --color --stat origin..HEAD${NORMAL}' to check local repository."
-
-#	If MARKITLOCAL AND same release number, notify user
-else
-	git tag -a ${FILE_RELEASE} -m "${FILE_MESSAGE}"
-	echo -e "\nFiles marked for  ${BOLD}local${NORMAL}  repository."
-	echo    "Enter '${BOLD}git log --graph --decorate --oneline --color --stat origin..HEAD${NORMAL}' to check local repository."
+#	If MARKITLOCAL, notify user how to view local commits
+elif [ "${MARKITLOCAL}" == "1" ] ; then
+	echo -e "\nFiles marked and stored in  ${BOLD}local${NORMAL}  repository."
+	echo    "View local commits example:  '${BOLD}git log --graph --decorate --oneline --color --stat origin..HEAD${NORMAL}'"
 fi
 
 #
