start 3.2 beta release; major code rewrite for #5

diff --git a/markit b/markit
--- a/markit
+++ b/markit
@@ -1,4 +1,6 @@
 #!/bin/bash
+#	markit	3.2.80	2018-02-11_23:53:12_CST uadmin six-rpi3b.cptx86.com 1.6-38-g874ab44 
+#	start 3.2 beta release; major code rewrite for #5 
 #	markit	3.1.79	2018-02-11_22:09:26_CST uadmin six-rpi3b.cptx86.com 1.6-37-g738b05e 
 #	testing failed login; cleanup debugging for #9, closes #8 
 #	markit	3.1.73	2018-02-11_21:28:53_CST uadmin six-rpi3b.cptx86.com 1.6-31-gbbb8b0e 
@@ -69,13 +71,14 @@ fi
 #	>>>	x	blank $1 & no, normal, all
 #	>>>		all files are new and not on GitHub (untracked) test no and all
 #	>>>		no files need markit
+#	>>>		dockerfile
 #	>>>	x	one file need markit
 #	>>>	 	several files need markit with different extensions complete case statement first
 #
 #	Check if in Git repository
 source /usr/share/bash-completion/completions/git
 if ! $( __gitdir > /dev/null 2>&1 ) ; then
-	echo -e "${0} ${LINENO} [WARNING]:	`pwd` Check if you are in a Git repository\n\tand you have GIT access permission.\n"	1>&2
+	echo -e "${0} ${LINENO} [WARNING]:	`pwd` Check if you are in a Git repository\n\tand you have GIT permission.\n"	1>&2
 	exit 0
 fi
 ###
@@ -98,6 +101,7 @@ if [ "$1" != "no" ] && [ "$1" != "normal" ] && [ "$1" != "all" ] && [ "$1" != ""
 	exit 0
 fi
 FILE_LIST=`git status -s --untracked-files=${UNTRACKED_FILES} | awk '{print $2}'`
+echo    "	=>	Debugging ${LINENO} ${FILE_NAME}   ${FILE_LIST}"
 #	Check if ${FILE_LIST} is zero length
 if [ -z "${FILE_LIST}" ] ; then
 	display_help
@@ -105,11 +109,20 @@ if [ -z "${FILE_LIST}" ] ; then
 	echo -e "${0} ${LINENO} [WARNING]:	No file(s) found to mark and push to GitHub.\n"	1>&2
 	exit 1
 fi
+#	Check if user has write permission
+	if ! $(touch ${TEMP_FILE} > /dev/null 2>&1 ) ; then
+		echo -e "${0} ${LINENO} [ERROR]:	${USER} does NOT have write permission\n\tin local Git repository."	1>&2
+		exit 1
+	fi
 #	Prompt for release number
+echo    "	=>	Debugging ${LINENO}"
 echo -e "Files to be marked and pushed to GitHub:\n${FILE_LIST}"
 echo    "Current release number: ${CURRENT_RELEASE} "
 echo -e "Enter release number to commit files to GitHub (example 3.01).\n\tPress enter to use ${CURRENT_RELEASE} release number."
 read     FILE_RELEASE
+#	Check if release number is newer than add tag reference with new release number
+#	>>>	   think about changing == to >= (are all release numbers? no A.01 ?)
+#	>>>	        is v1.0 > v2.0 or < v1.1 
 if [ -z ${FILE_RELEASE} ] ; then
 	FILE_RELEASE=${CURRENT_RELEASE}
 fi
@@ -118,66 +131,8 @@ if [ -z ${FILE_RELEASE} ] ; then
 	echo -e "${0} ${LINENO} [ERROR]:	No release number to mark and push to GitHub.\n"       1>&2
 	exit 1
 fi
+echo    "	=>	Debugging ${LINENO}"
 echo -e "${0} ${LINENO} [INFO]:	Using release number: ${FILE_RELEASE}"	1>&2
-###	CUT HERE <<<<<<   -> when adding case statement
-#	Prompt for single-line beginning comment character(s)
-echo -e "Enter single-line beginning comment character(s) to use\n   (example: # // -- ' ! s !* -- // % ;;   /* <!-- <!--- {- /** --[[ %{ (* <# ):"
-read BEGIN_COMMENT_CHAR
-#
-if [ -z ${BEGIN_COMMENT_CHAR} ] ; then
-	display_help
-	echo -e "${0} ${LINENO} [ERROR]:        Single-line comment character(s) is required.\n"       1>&2
-	exit 1
-fi
-###
-#	>>>	This test code will need to be placed in the for loop so each file will use or prompt for the correct single-line beginning comment
-#	>>>	create a case statement if other non-extension files like dockerfile need support
-#	>>>	Add support for dockerfile ('#') before prompt for single-line beginning comment character 
-#	if [ "${FILE_RELEASE}" == "dockerfile" ] ; then
-#	   BEGIN_COMMENT_CHAR="#	"
-#	   END_COMMENT_CHAR=""
-#	else
-### >>> insert case statement HERE <<<
-#	fi
-#		
-#	single-line comment character(s) matching file extension
-#	ONLY SUPPORT single-line comments NOT multiple line block comment
-#	case $variable in
-#	   sh|pl|PL|py|rb|ps1|php|php3|php4|ph3|ph4|R|yml|yaml|mk|MK)
-#	      # UNIX shell(sh) perl(pl|PL) python(py) ruby(rb) PowerShell(ps1) PHP(php|php3|php4|ph3|ph4) R(R) YAML(yml|yaml) makefile(mk|MK)
-#	      BEGIN_COMMENT_CHAR="#	"
-#	      END_COMMENT_CHAR=""
-#	      ;;
-#	   c|h|H|hpp|hxx|Hxx|HXX|)
-#	      # c(c) C header(h|H|hpp) C++ header(hxx|Hxx|HXX) 
-#	      BEGIN_COMMENT_CHAR="/* "
-#	      END_COMMENT_CHAR=" */"
-#	      ;;
-#	   cc|cpp|c++|cxx|go|java|class|jar|js|kt|kts|p|pp|pas|rs|rlib|scala|sc)
-#	      # C++(cc|cpp|c++|cxx) Go(g0) Java(java|class|jar) JavaScript(js) Kotlin(kt|kts) Pascal (p|pp|paa) Rust(rs|rlib) Scala(scala|sc)
-#	      BEGIN_COMMENT_CHAR="// "
-#	      END_COMMENT_CHAR=""
-#	      ;;
-#	   xml|html|htm)
-#	      # XML(xml) HTML (html|htm) 
-#             BEGIN_COMMENT_CHAR="<!-- "
-#             END_COMMENT_CHAR=" -->"
-#	      ;;
-#	   *)
-#	      Prompt for single-line beginning comment character(s)
-#	      echo -e "Enter single-line beginning comment character(s) to use\n   (example: # // -- ' ! C !* -- // % ;;  ||  /* <!-- <!--- {- /** --[[ %{ (* <# )"
-#	      read BEGIN_COMMENT_CHAR
-#	      if [ -z ${BEGIN_COMMENT_CHAR} ] ; then
-#	       	display_help
-#		echo -e "${0} ${LINENO} [ERROR]:        Single-line comment character(s) is required.\n"       1>&2
-#	        exit 1
-#	      fi
-#	      echo -e "Enter single-line ending comment character(s) to use\n (example: */ --> ---> -} */ --]] %} *) #> )"
-#	      read END_COMMENT_CHAR
-#	      ;;
-#	esac
-###
-###	CUT HERE <<<<<<    -> when adding case statement
 #	Prompt for single line change description
 echo -e "Enter a one line description about the changes\n   (example: description of changes; closes #12, resolves #14, fixed #22):"
 read FILE_MESSAGE
@@ -186,14 +141,68 @@ if [ -z "${FILE_MESSAGE}" ] ; then
 	echo -e "${0} ${LINENO} [ERROR]:        Single-line description is required.\nTo display changes between commits, git diff <file_name>."       1>&2
 	exit 1
 fi
+echo    "	=>	Debugging ${LINENO} ${FILE_NAME}   ${FILE_LIST}"
 #	Mark each file
 for FILE_NAME in ${FILE_LIST} ; do
-###	INSERT HERE <<<<<< if then dockerfile else (case statement) fi -> when adding case statement
-#	Check if user has write permission
-	if ! $(touch ${TEMP_FILE} > /dev/null 2>&1 ) ; then
-		echo -e "${0} ${LINENO} [ERROR]:	${USER} does NOT have write permission\n\tin local Git repository."	1>&2
-		exit 1
+echo    "	=>	Debugging ${LINENO} ${FILE_NAME}   ${FILE_LIST}"
+# >>>	Create a case statement if other non-extension files like dockerfile need support
+	if [ "${FILE_NAME}" == "dockerfile" ] ; then
+echo    "	=>	Debugging ${LINENO} ${FILE_NAME}   ${FILE_LIST}"
+		BEGIN_COMMENT_CHAR="#	"
+		END_COMMENT_CHAR=""
+echo    "	=>	Debugging ${LINENO} ${FILE_NAME}   ${FILE_LIST}"
+	else
+echo    "	=>  153	Debugging ${LINENO} ${FILE_NAME}   ${FILE_LIST}"
+echo    "	=>  153	Debugging ${LINENO} ${FILE_NAME}   ${FILE_LIST}"
+# >>>	This does not work if the last character is '.'
+echo    "	=>  153	Debugging ${LINENO} ${FILE_NAME}   ${FILE_LIST}"
+echo    "	=>  153	Debugging ${LINENO} ${FILE_NAME}   ${FILE_LIST}"
+#	echo ${FILE_NAME} ${FILE_EXTENSION}
+echo    "	=>  159	Debugging ${LINENO} ${FILE_NAME}   ${FILE_LIST}"
+	FILE_EXTENSION=${FILE_NAME##*\.}
+echo    "	=>  159	Debugging ${LINENO} ${FILE_NAME}   ${FILE_LIST}"
+	echo ${FILE_NAME} ${FILE_EXTENSION}
+echo    "	=>	Debugging ${LINENO}"
+####################3###
+#	Single-line comment character(s) matching file extension
+#	ONLY SUPPORT single-line comments NOT multiple line block comment
+	case ${FILE_EXTENSION} in
+		sh|pl|PL|py|rb|ps1|php|php3|php4|ph3|ph4|R|yml|yaml|mk|MK)
+#		UNIX shell(sh) perl(pl|PL) python(py) ruby(rb) PowerShell(ps1) PHP(php|php3|php4|ph3|ph4) R(R) YAML(yml|yaml) makefile(mk|MK)
+			BEGIN_COMMENT_CHAR="#	"
+			END_COMMENT_CHAR=""
+			;;
+#		c|h|H|hpp|hxx|Hxx|HXX|)
+#		c(c) C header(h|H|hpp) C++ header(hxx|Hxx|HXX) 
+#			BEGIN_COMMENT_CHAR="/* "
+#			END_COMMENT_CHAR=" */"
+#			;;
+		cc|cpp|c++|cxx|go|java|class|jar|js|kt|kts|p|pp|pas|rs|rlib|scala|sc)
+#		C++(cc|cpp|c++|cxx) Go(g0) Java(java|class|jar) JavaScript(js) Kotlin(kt|kts) Pascal (p|pp|paa) Rust(rs|rlib) Scala(scala|sc)
+			BEGIN_COMMENT_CHAR="// "
+			END_COMMENT_CHAR=""
+			;;
+		xml|html|htm)
+#		XML(xml) HTML (html|htm) 
+			BEGIN_COMMENT_CHAR="<!-- "
+			END_COMMENT_CHAR=" -->"
+			;;
+		*)
+#			Prompt for single-line beginning comment character(s)
+			echo -e "Enter single-line beginning comment character(s) for ${FILE_NAME}\n   (example: # // -- ' ! C !* -- // % ;;  ||  /* <!-- <!--- {- /** --[[ %{ (* <# )"
+			read BEGIN_COMMENT_CHAR
+			if [ -z ${BEGIN_COMMENT_CHAR} ] ; then
+				display_help
+				echo -e "${0} ${LINENO} [ERROR]:        Single-line comment character(s) is required.\n"       1>&2
+				exit 1
+			fi
+			echo -e "Enter single-line ending comment character(s) to use\n (example: */ --> ---> -} */ --]] %} *) #> )"
+			read END_COMMENT_CHAR
+			;;
+	esac
+echo    "	=>	Debugging ${LINENO} ${FILE_NAME}   ${FILE_LIST}"
 	fi
+echo    "	=>	Debugging ${LINENO} ${FILE_NAME}   ${FILE_LIST}"
 	head -1 ${FILE_NAME} >> ${TEMP_FILE}
 	echo "${BEGIN_COMMENT_CHAR}	${FILE_NAME}	${FILE_RELEASE}.`git rev-list HEAD | wc -l`	${TIME_STAMP} ${USER} `hostname -f` `git describe` ${END_COMMENT_CHAR}" >> ${TEMP_FILE}
 	echo "${BEGIN_COMMENT_CHAR}	${FILE_MESSAGE} ${END_COMMENT_CHAR}" >> ${TEMP_FILE}
@@ -202,12 +211,11 @@ for FILE_NAME in ${FILE_LIST} ; do
 	rm ${TEMP_FILE}
 #	Add file contents to the index
 	git add ${FILE_NAME}
+echo    "	=>	Debugging ${LINENO} ${FILE_NAME}   ${FILE_LIST}"
 done
 #	Commit staged file(s) for Git push
 	git commit -m "${FILE_MESSAGE}"
-#	Check if release number is newer than add tag reference with new release number
-#	>>>	   think about changing == to >= (are all release numbers? no A.01 ?)
-#	>>>	        is v1.0 > v2.0 or < v1.1 
+#	>>> ????????????
 if ! [ "${FILE_RELEASE}" == "${CURRENT_RELEASE}" ] ; then
 	git tag -a ${FILE_RELEASE} -m "${FILE_MESSAGE}"
 #	Push changes to GitHub repository
