parsed MARKIT_FILE now put it into one line with error detction #29

diff --git a/markcheck b/markcheck
--- a/markcheck
+++ b/markcheck
@@ -1,4 +1,6 @@
 #!/bin/bash
+#	markcheck  3.28.169  2018-08-02_23:08:58_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.27  
+#	   parsed MARKIT_FILE now put it into one line with error detction #29 
 #	markcheck  3.27.168  2018-08-02_15:22:11_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.26  
 #	   process command arguments #29 
 #	markcheck  3.26.167  2018-08-02_13:57:07_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.25  
@@ -38,7 +40,6 @@ if ! $( __gitdir > /dev/null 2>&1 ) ; then
 fi
 #	Check if remote git repository has been setup #28
 git rev-list HEAD 1> /dev/null || { echo -e "\n${NORMAL}${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:	Remote repository has\n\tnot been setup or git cloned <remote-repository> was not used to pull\n\tremote repository before using markit." ; exit 1; }
-
 #
 ##################################
 #	notes:
@@ -62,7 +63,6 @@ if [ "${1}" == "" ] ; then
 	display_help
 	exit 0
 fi
-	set -x
 #	if -f or --file is given then the path must be included because it may not be excutable and/or in PATH
 if [ "${1}" == "--file" ] || [ "${1}" == "-f" ] ; then
 	#       Check if argument 2 is blank
@@ -73,20 +73,28 @@ if [ "${1}" == "--file" ] || [ "${1}" == "-f" ] ; then
 	fi
 	MARKIT_FILE = ${2}
 else
-	MARKIT_FILE = ${1}
+	#	Locate file in the PATH
+	echo -e "${LINENO} argument 1 = ${1}"
+	TEMP=`whereis "${1}"`
+	echo  "${LINENO} temp = ${TEMP}"
+	MARKIT_FILE=$(echo ${TEMP} | awk {'print $2'} )
+	echo  "${LINENO} MARKIT_FILE = ${MARKIT_FILE}"
+exit
+	MARKIT_FILE=`whereis ${1}` | awk {'print$2'} 1> /dev/null || { echo -e "\n${NORMAL}${0} ${LINENO} [${BOLD}ERROR${NORMAL}]: ${MARKIT_FILE} file not found in PATH\n${PATH}\n >>>> is it executable <<<<<< remove this later  <<<<< " ; exit 1; }
 fi
-	
-	#       Check if MARKIT_FILE file exists and has a size greater than zero
-	if [ ! -e ${MARKIT_FILE} ] || [ ! -s ${MARKIT_FILE} ] ; then
-        	echo -e "${NORMAL}\n${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:     ${MARKIT_FILE} file not found\n" 1>&2
-		exit 1
-	fi
-###
-MARKIT_FILE=${1}
 
-echo ${PATH}
-#	this will work it the file is an excutable in the PATH
-whereis ${1}
+
+echo  ${LINENO}${MARKIT_FILE}
+exit
+
+
+
+#       Check if MARKIT_FILE file exists and has a size greater than zero
+if [ ! -e ${MARKIT_FILE} ] || [ ! -s ${MARKIT_FILE} ] ; then
+       	echo -e "${NORMAL}\n${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:     ${MARKIT_FILE} file is not found or is empty\n" 1>&2
+	exit 1
+fi
+###
 
 
 head -2 ${0} | awk {'print$2"\t"$3'}
